---
version: "3"

services:
  3x-ui-ext:
    image: ghcr.io/theimaginationless/3x-ui-ext:latest
    container_name: 3x-ui-ext
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped
